name: lab07
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Agrega tus assets aquí
  assets:
    - assets/flutter_logo.png
    - assets/data_science.png
    - assets/web_dev.png
    - assets/graphic_design.png
